apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-secrets
  namespace: cluster-secrets
spec:
  provider:
    kubernetes:
      remoteNamespace: cluster-secrets
      server:
        url: "https://kubernetes.default.svc"
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: cluster-secrets
      auth:
        serviceAccount:
          name: cluster-secrets
          namespace: cluster-secrets
  conditions:
    - namespaceSelector:
        matchLabels:
          external-secrets/useClusterStore: "cluster-secrets"