apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cluster-secrets
  namespace: cluster-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eso-store-role
subjects:
  - kind: ServiceAccount
    name: cluster-secrets
    namespace: cluster-secrets
