apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-secrets
  namespace: cluster-secrets
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-cluster-secrets
  namespace: cluster-secrets