apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: plex
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
  data:
    - secretKey: claim
      remoteRef:
        key: plex
        conversionStrategy: Default
        decodingStrategy: None
        property: claim