apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/configmap.yaml
  - resources/deployment.yaml
  - resources/ingress.yaml
  - resources/namespace.yaml
  - resources/service.yaml

images:
  - name: cr.hotio.dev/hotio/overseerr
    newTag: release-1.32.5

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: overseerr