apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://argoproj.github.io/argo-helm'
    targetRevision: 5.33.4
    chart: argo-cd
    helm:
      values: |-
        server:
          ingress:
            enabled: "true"
            annotations:
              cert-manager.io/cluster-issuer: lets-encrypt
              kubernetes.io/tls-acme: "true"
              nginx.ingress.kubernetes.io/ssl-passthrough: "true"
              nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
            hosts:
              - argocd.sergi.cool
            tls:
            - secretname: argocd-ingress-tls
              hosts:
                - argocd.sergi.cool
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true