apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flaresolverr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: ghcr.io/flaresolverr/flaresolverr:latest
spec:
  project: default
  source:
    path: flaresolverr
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  destination:
    namespace: flaresolverr
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

