apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gpu-plugin
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: deployments/gpu_plugin
    repoURL: https://github.com/intel/intel-device-plugins-for-kubernetes
    targetRevision: v0.26.1
  destination:
    namespace: gpu-plugin
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true