apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: ghcr.io/benphelps/homepage:v0.6.x
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://jameswynn.github.io/helm-charts'
    targetRevision: 1.2.0
    chart: homepage
    helm:
      values: |-
        enableRbac: true
        serviceAccount:
          create: true
        ingress:
          main:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: lets-encrypt
              nginx.ingress.kubernetes.io/auth-type: basic
              nginx.ingress.kubernetes.io/auth-secret: basic-auth
              nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
            hosts:
              - host: home.sergi.cool
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - secretName: homepage-ingress-tls
                hosts:
                  - home.sergi.cool
        config:
          bookmarks: {}
          services:
            - Group A:
              - Sonarr:
                  icon: https://raw.githubusercontent.com/Sonarr/Sonarr/develop/Logo/Sonarr.svg
                  href: https://sonar.sergi.cool/
                  description: Series management
                  widget:
                    - type: sonarr
                      url: http://sonarr.sonarr
                      key: '{{"{{"}}HOMEPAGE_VAR_SERVICE_API_KEY{{"}}"}}'
                      enableQueue: true
          widgets:
            - resources:
                backend: kubernetes
                expanded: true
                cpu: true
                memory: true
                disk: /app/config
            - search:
                provider: duckduckgo
                target: _blank
          kubernetes:
            mode: cluster
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: homepage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true