apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: homepage=ghcr.io/benphelps/homepage
    argocd-image-updater.argoproj.io/homepage.update-strategy: newest-build
    argocd-image-updater.argoproj.io/homepage.allow-tags: regexp:^v0.6.+$
spec:
  project: default
  source:
    path: homepage
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  destination:
    namespace: homepage
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true