apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: plex=plexinc/pms-docker
    argocd-image-updater.argoproj.io/plex.update-strategy: latest
    argocd-image-updater.argoproj.io/plex.pull-secret: pullsecret:argocd/dockerhub-secret
spec:
  project: default
  source:
    path: plex
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  destination:
    namespace: plex
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true