apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prowlarr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: prowlarr=hotio/prowlarr
    argocd-image-updater.argoproj.io/prowlarr.update-strategy: newest-build
    argocd-image-updater.argoproj.io/prowlarr.allow-tags: regexp:^release-1.+$
spec:
  project: default
  source:
    path: prowlarr
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  destination:
    namespace: prowlarr
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true