apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qbittorrent
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: qbittorrent=hotio/qbittorrent
    argocd-image-updater.argoproj.io/qbittorrent.update-strategy: newest-build
    argocd-image-updater.argoproj.io/qbittorrent.allow-tags: regexp:^release-4.+$
spec:
  project: default
  source:
    path: qbittorrent
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  destination:
    namespace: qbittorrent
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true