apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: radarr=hotio/radarr
    argocd-image-updater.argoproj.io/radarr.update-strategy: newest-build
    argocd-image-updater.argoproj.io/radarr.allow-tags: regexp:^release-4.+$
spec:
  project: default
  source:
    path: radarr
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  destination:
    namespace: radarr
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true