apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: sonarr=hotio/sonarr
    argocd-image-updater.argoproj.io/sonarr.update-strategy: newest-build
    argocd-image-updater.argoproj.io/sonarr.allow-tags: regexp:^release-3.+$
spec:
  project: default
  source:
    path: sonarr
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  destination:
    namespace: sonarr
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true