apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
  finalizers:
    - resources-finalizer.vaultwarden.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: vaultwarden
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: vaultwarden
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
