apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/configmap.yaml
  - resources/deployment.yaml
  - resources/ingress.yaml
  - resources/namespace.yaml
  - resources/service.yaml

images:
  - name: cr.hotio.dev/hotio/radarr
    newTag: release-4.5.2.7388

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: radarr