apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
spec:
  template:
    spec:
      containers:
        - name: radarr
          image: cr.hotio.dev/hotio/radarr:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: radarr-config
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /config
              name: radarr-config
            - mountPath: /downloads
              name: radarr-downloads
            - mountPath: /movies
              name: radarr-movies
      volumes:
        - name: radarr-config
          hostPath:
            path: /opt/radarr/config
            type: Directory
        - name: radarr-downloads
          hostPath:
            path: /opt/media/downloads
            type: Directory
        - name: movies
          hostPath:
            path: /opt/media/movies
            type: Directory
