apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
spec:
  template:
    spec:
      containers:
        - name: radarr
          image: hotio/radarr:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: radarr-config
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /downloads
              name: downloads
            - mountPath: /movies
              name: movies
      volumes:
        - name: config
          hostPath:
            path: /opt/radarr/config
            type: Directory
        - name: downloads
          hostPath:
            path: /opt/media/downloads
            type: Directory
        - name: movies
          hostPath:
            path: /opt/media/movies
            type: Directory
