apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: basic-auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
  data:
    - secretKey: auth
      remoteRef:
        key: basic-auth
        conversionStrategy: Default
        decodingStrategy: None
        property: auth