apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
spec:
  template:
    spec:
      containers:
        - name: prowlarr
          image: cr.hotio.dev/hotio/prowlarr:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: prowlarr-config
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /downloads
              name: downloads
      volumes:
        - name: config
          hostPath:
            path: /opt/prowlarr/config
            type: Directory
        - name: downloads
          hostPath:
            path: /opt/media/downloads
            type: Directory
