apiVersion: apps/v1
kind: Deployment
metadata:
  name: overseerr
spec:
  template:
    spec:
      containers:
        - name: overseerr
          image: hotio/overseerr:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: overseerr-config
          volumeMounts:
            - mountPath: /config
              name: config
      volumes:
        - name: config
          hostPath:
            path: /opt/overseerr/config
            type: Directory
