apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vaultwarden
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: vaultwarden
        conversionStrategy: Default
        decodingStrategy: None
        property: username
    - secretKey: password
      remoteRef:
        key: vaultwarden
        conversionStrategy: Default
        decodingStrategy: None
        property: password